#!/usr/bin/env ansible-playbook

---

- hosts: all
  strategy: free
  gather_facts: true
  become: true

- hosts: all
  connection: local
  strategy: free
  gather_facts: false
  become: false
  roles:
  - perfide.fetch-facts

...
